artefacts_root: artefacts


data_ingestion:
  root_dir: artefacts/data_ingestion
  source_URL: https://github.com/donadviser/datasets/raw/master/data-don/cat-dog-data.zip
  local_data_file: artefacts/data_ingestion/data.zip
  unzip_dir: artefacts/data_ingestion


prepare_base_model:
  root_dir: artefacts/prepare_base_model
  base_model_path: artefacts/prepare_base_model/base_model.h5
  updated_base_model_path: artefacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artefacts/prepare_callbacks
  tensorboard_root_log_dir: artefacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artefacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artefacts/training
  trained_model_path: artefacts/training/model.h5
